[package]
name = "sotf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
rusqlite = "0.31.0"

[lib]
name = "sotf"
path = "src/lib.rs"

[[bin]]
name = "sotf"
path = "src/main.rs"
