[package]
name = "sotf-python"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sotf_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
sotf = { path = "../sotf" }
